# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - src-tauri/target/

stages:
  - install
  - build
  - test
  - compile

install-front:
  image: node:16
  stage: install
  script:
    - yarn install
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules

install-testing:
  image: node:16
  stage: install
  script:
    - yarn --cwd webdriver/webdriverio install
  artifacts:
    expire_in: 1 hour
    paths:
      - webdriver/webdriverio/node_modules

build-front:
  image: node:16
  stage: build
  script:
    - yarn build
  dependencies:
    - install-front
  artifacts:
    expire_in: 1 hour
    paths:
      - dist

unit-test:
  image: node:16
  stage: test
  dependencies:
    - build-front
    - install-testing
  before_script:
    # Install WebDriver
    - apt-get update && apt-get upgrade -y --no-install-recommends webkit2gtk-4.0 webkit2gtk-driver xvfb xauth
  script:
    - xvfb-run yarn test

lint-front:
  image: node:16
  stage: test
  dependencies:
    - install-front
  script:
    - yarn lint

compile-binary:
  image: rust:1-buster
  stage: compile
  dependencies:
    - unit-test
    - build-front
  script:
    - ./bin/tauri build
  artifacts:
    expire_in: 1 day
    paths:
      - src-tauri/target/release/bundle/
      - src-tauri/target/release/CHDesktop*
