version: '3'

services:
    app:
        image: registry.gitlab.com/chstudio-lab/gehealthcare/pocs/ch-desktop
        network_mode: host
        environment:
            - DISPLAY=host.docker.internal:0
        working_dir: /srv
        volumes:
            - './:/srv'
            - './src-tauri/target/cargo-local/git:/home/.cargo/git'
            - './src-tauri/target/cargo-local/registry:/home/.cargo/registry'
            - './docker/entrypoint.bash:/bin/entrypoint'
        command: ['yarn', 'tauri:serve']
